name: tlssec
services:
  dev-cli:
    image: tlssec:dev
    pull_policy: never
    build:
      context: .
      target: dev
    # Mount source code for live editing
    volumes:
    - ./src:/opt/app/src
    entrypoint:
    - sh
    depends_on:
      db:
        condition: service_healthy
  cli:
    image: tlssec
    pull_policy: never
    build:
      context: .
    entrypoint:
    - sh
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_PASSWORD: local-test-password-PZ9dVzwew3Xe
      POSTGRES_DB: tlssec
    # TODO: add healthcheck
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.local
      PGADMIN_DEFAULT_PASSWORD: local-test-password-FKl7sfIpbEpD
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
    ports:
    - 8080:80
    links:
    - db

# TODO: use docker compose secret instead of env var
# TODO: use named volume
# TODO: autoconnect pgadmin
# TODO: create schema `tlssec` and user specific to schema
