[project]
name = "tlssec"
version = "0.1.0"
description = "TLS security monitoring toolkit"
readme = "README.md"
authors = [
    { name = "Apiwat Chantawibul", email = "billiska@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "click>=8.3.2",
    "lxml>=6.1.1",
    "pandas>=3.0.3",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.50",
    "ssh-audit>=3.9.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
]

[project.scripts]
tlssec = "tlssec.cli:cli"

[project.optional-dependencies]
analysis = [
    "bottleneck>=1.6.0",
    "ipympl>=0.10.0",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.7",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "7 days"
# NOTE: Add specifically to use 3.9.0 faster. TODO: Remove soon.
exclude-newer-package = {ssh-audit = "3 days"}

[tool.pytest]
# Deselect slow tests by default. Use `-m ''` to include slow tests.
addopts = ["-m", "not slow"]
markers = [
    "slow: take a long time to run",
]
asyncio_mode = "auto"
